# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168xjVz_5V5oIKYOq3pVhSIUxOr8kuRSY
"""



import pandas as pd
import pickle

# --- Load the model and encoders ---
# Ensure these files are available in the same directory as your Streamlit app or accessible via path
try:
    with open('linear_regression_model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('label_encoders.pkl', 'rb') as f: # You must save label_encoders dictionary separately
        label_encoders = pickle.load(f)
    st.success("Model and encoders loaded successfully!")
except FileNotFoundError:
    st.error("Error: Model or label encoders file not found. Please ensure 'linear_regression_model.pkl' and 'label_encoders.pkl' are in the same directory as this app.")
    st.stop() # Stop the app if files are not found

st.title("Salary Prediction App")
st.write("Enter the details to predict the salary.")

# --- Input Features ---
st.header("Enter Features")

# Features from X_train: 'Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'

rating = st.slider("Rating (0.0 to 5.0)", min_value=0.0, max_value=5.0, value=3.8, step=0.1)

# Categorical features using selectbox to ensure valid encoded values
company_name_options = list(label_encoders['Company Name'].classes_)
company_name_input = st.selectbox("Company Name", options=company_name_options, index=0)

job_title_options = list(label_encoders['Job Title'].classes_)
job_title_input = st.selectbox("Job Title", options=job_title_options, index=0)

salaries_reported = st.number_input("Salaries Reported", min_value=1, value=3)

location_options = list(label_encoders['Location'].classes_)
location_input = st.selectbox("Location", options=location_options, index=0)

employment_status_options = list(label_encoders['Employment Status'].classes_)
employment_status_input = st.selectbox("Employment Status", options=employment_status_options, index=0)

job_roles_options = list(label_encoders['Job Roles'].classes_)
job_roles_input = st.selectbox("Job Roles", options=job_roles_options, index=0)

# --- Prediction Button ---
if st.button("Predict Salary"):
    # Create a DataFrame for prediction
    # Ensure column order matches the training data (X_train)
    input_data = pd.DataFrame([[
        rating,
        company_name_input, # Will be encoded
        job_title_input,    # Will be encoded
        salaries_reported,
        location_input,     # Will be encoded
        employment_status_input, # Will be encoded
        job_roles_input     # Will be encoded
    ]], columns=['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'])

    # Apply label encoding to input categorical features
    # Iterate through categorical columns based on label_encoders keys
    for col in ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']:
        if col in input_data.columns:
            # Transform the selected string value to its numerical representation
            # .transform expects an iterable, so wrap the single value in a list
            input_data[col] = label_encoders[col].transform([input_data[col].iloc[0]])[0]

    # Make prediction
    prediction = model.predict(input_data)

    st.success(f"Predicted Salary: ₹{prediction[0]:,.2f}")

import os


if os.path.exists('requirements.txt'):
    print("requirements.txt generated successfully!")
    with open('requirements.txt', 'r') as f:
        print(f.read())
else:
    print("Failed to generate requirements.txt.")
