# -*- coding: utf-8 -*-
"""SupervisedLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlWvvfNX50bYiE8PevsX2WwCpB7hrri6
"""

import pandas as pd

df = pd.read_csv("/content/Salary_Dataset_DataScienceLovers.csv")
df

df.isnull().sum()

company_name_mode = df['Company Name'].mode()[0]
df['Company Name'] = df['Company Name'].fillna(company_name_mode)

print('Null values after filling:')
display(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

print(f"Categorical columns to encode: {list(categorical_cols)}")

# Apply Label Encoding to each categorical column
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print('\nDataFrame after Label Encoding:')
display(df.head())

# Display an example of the encoding mapping for 'Company Name'
if 'Company Name' in label_encoders:
    print('\nLabel Encoding mapping for "Company Name":')
    company_name_le = label_encoders['Company Name']
    # Create a DataFrame to show the mapping
    mapping_df = pd.DataFrame({'Original': company_name_le.classes_, 'Encoded': company_name_le.transform(company_name_le.classes_)})
    display(mapping_df.head(10)) # Display first 10 mappings for brevity

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("Linear Regression model trained successfully!")

from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# Initialize models
models = {
    'Linear Regression': model, # Already trained
    'SVR': SVR(),
    'KNeighbors Regressor': KNeighborsRegressor(),
    'Decision Tree Regressor': DecisionTreeRegressor(random_state=42),
    'Random Forest Regressor': RandomForestRegressor(random_state=42)
}

# Train additional models
for name, current_model in models.items():
    if name != 'Linear Regression': # Linear Regression is already trained
        print(f"Training {name}...")
        current_model.fit(X_train, y_train)
        print(f"{name} trained successfully!")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Dictionary to store evaluation metrics for each model
metrics_results = {
    'Model': [],
    'MAE': [],
    'MSE': [],
    'RMSE': [],
    'R-squared': []
}

# Evaluate each model
for name, model in models.items():
    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Calculate evaluation metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    # Store the results
    metrics_results['Model'].append(name)
    metrics_results['MAE'].append(mae)
    metrics_results['MSE'].append(mse)
    metrics_results['RMSE'].append(rmse)
    metrics_results['R-squared'].append(r2)

# Convert results to a DataFrame for better viewing
metrics_df = pd.DataFrame(metrics_results)

print("Model Evaluation Metrics:")
display(metrics_df.round(2))

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set_style("whitegrid")

# Create subplots for each metric
fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle('Comparison of Regression Model Performance', fontsize=16)

# Plot MAE
sns.barplot(ax=axes[0, 0], x='Model', y='MAE', data=metrics_df.sort_values(by='MAE', ascending=True), palette='viridis', hue='Model', legend=False)
axes[0, 0].set_title('Mean Absolute Error (MAE)')
axes[0, 0].tick_params(axis='x', rotation=45)

# Plot MSE
sns.barplot(ax=axes[0, 1], x='Model', y='MSE', data=metrics_df.sort_values(by='MSE', ascending=True), palette='magma', hue='Model', legend=False)
axes[0, 1].set_title('Mean Squared Error (MSE)')
axes[0, 1].tick_params(axis='x', rotation=45)

# Plot RMSE
sns.barplot(ax=axes[1, 0], x='Model', y='RMSE', data=metrics_df.sort_values(by='RMSE', ascending=True), palette='cividis', hue='Model', legend=False)
axes[1, 0].set_title('Root Mean Squared Error (RMSE)')
axes[1, 0].tick_params(axis='x', rotation=45)

# Plot R-squared
sns.barplot(ax=axes[1, 1], x='Model', y='R-squared', data=metrics_df.sort_values(by='R-squared', ascending=False), palette='plasma', hue='Model', legend=False)
axes[1, 1].set_title('R-squared')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

import pickle

# Identify the best model based on R-squared (or other preferred metric)
# From the metrics_df, Linear Regression has the highest R-squared (0.05)
best_model_name = 'Linear Regression'
best_model = models[best_model_name]

# Define the filename for the saved model
model_filename = f'{best_model_name.replace(" ", "_").lower()}_model.pkl'

# Save the best model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"The best model '{best_model_name}' has been saved as '{model_filename}'.")